language: ruby
rvm:
- 2.2.3
bundler_args: "--without production"
before_script:
- cp config/intrasearch.yml.example config/intrasearch.yml
- cp config/restforce.yml.example config/restforce.yml
before_install:
- curl -O https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.4.deb
  && sudo dpkg -i --force-confnew elasticsearch-1.7.4.deb
services:
- elasticsearch
addons:
  code_climate:
    repo_token:
      secure: ffRFcJVQ0r2btgEpC9GTYWfLY3vs0KUZuSlpTeRZldopjO6qsuW9JhpzeMby3GmXjNUolUH/A/sx1Za7suPYTbVFa1s/ITycNz6DX90fHIekhdk0rFy5ZGQgwjf/3ANE/LqQXdh+/UPJ6qgx6156fP9Av9Ql6XSi2g6t5KbqhuRtl4h1sv96JS+Xi5LDVQ9COrJtNfBb0XZSxnTEO/8ARpq4n5WB8O0IQxiIFeGsCdbmD1L1Zt66SuYbMto3Novgn/lrAYhE0ke8JuRlebSMsLQuVzjx+hqi/KPljRNGhjXYSDM3/gVWPl9nzcf8uvU4XZt9kCTJWcrmppvHkjFCtevpMPGZIE6+BYAiVxbhO1G4crMwTP/91ijMa1VJSCHqUuF2hp2QiUZqMOWMbZ0q8wyH5xwEl2WvJ9/yqg8+zqeOJyiSg6fGqqo7FiIUlNufc7X+VQ+Ryw7HSeLYzy4bpTV7lZDLltw9INbltDXP1BDl/tu+KWDL9/5gwZsAFF87Szuwryg0uNcXSbv44u5zcvuJnlaK/GRSsfAF15w3vGxX0tM5q0IhbSr6gTWesUzpGhk9hbwpYdhYpLLfNt5inELJLhFwd+S/gz83MJxPQ5r8IBe7MTj2yXGFV1VFxdp6eJub/zPcCTHoM0r/i3pQWFsgy3IFNs7o6UhOI0TvUSs=
